
// PRODUCTS RELATED CONSTANTS

export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS"
export const SET_PRODUCTS = "SET_PRODUCTS"
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR"

// AUTH
export const LOGIN_USER = "LOGIN_USER"
export const LOG_OUT = "LOG_OUT"
export const ON_LOGIN = "ON_LOGIN"
export const ON_LOGTOUT = "ON_LOGOUT"


// COMMON CONSTANT

export const CLOSE_COMMON_LOADER = "CLOSE_COMMON_LOADER"
export const SET_SELECTED_MENU = "SET_SELECTED_MENU"
export const SET_USER_DETAILS = "SET_USER_DETAILS"